site_name: Umang Wellness External Docs


theme:
  name: material

  features:
    - navigation.indexes

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye
        name: Switch to dark mode
      primary: light green
      accent: green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
      primary: blue
      accent: deep purple




nav:
    - Welcome to Umang Wellness Guides: 'index.md'
    - General Guides:
      - general/index.md
      - Contact Support: 'general/contact-us.md'
      - View FAQs: 'general/view-faqs.md'
      - Reach Sign Up Page: 'general/reach-sign-up-page.md'
      - Reach Sign In Page: 'general/reach-sign-in-page.md'
      - Give Feedback: 'general/give-feedback.md'
      - View About Section: 'general/view-about-section.md'
      - View Cookie Policy: 'general/view-cookie-policy.md'
      - View Terms and Conditions: 'general/view-terms-and-conditions.md'
      - View Privacy Policy: 'general/view-privacy-policy.md'
      - View Sitemap: 'general/view-sitemap.md'
      - View Version History: 'general/view-version-history.md'
      - View Social Links: 'general/view-social-links.md'
      - Gift Voucher: 'general/gift-voucher.md'
    - Client Guides:
      - client/index.md
      - Sign In: 'client/client-sign-in.md'
      - Sign Out: 'client/client-sign-out.md'
      - Find Counsellor: 'client/find-counsellor.md'
      - View Profile: 'client/view-profile.md'
      - Edit Profile: 'client/edit-profile.md'
      - View Counsellor List: 'client/view-counsellor-list.md'
      - Book Session: 'client/book-session.md'
    - Counsellor Guides:
      - counsellor/index.md
      - Sign In: 'counsellor/counsellor-sign-in.md'
      - Sign Out: 'counsellor/counsellor-sign-out.md'
      - View Profile: 'counsellor/view-profile.md'
      - Edit Profile: 'counsellor/edit-profile.md'
      - Change Available Timings: 'counsellor/change-available-timings.md'
      - View/Edit My Pricings: 'counsellor/view-edit-my-pricings.md'
      - View Clients: 'counsellor/view-clients.md'
  
    