site_name: Umang Wellness External Docs


theme:
  name: material

  features:
    - navigation.indexes

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye
        name: Switch to dark mode
      primary: light green
      accent: green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
      primary: blue
      accent: deep purple




nav:
    - Welcome to Umang Wellness Guides: 'index.md'
    - Business Flow Guide: './business-flow-guide.md'
    - Semantic Versioning: './semantic-versioning.md'
    - Tech Stack & Code Architecture/Organisation: './architecture.md'
  
    