site_name: Umang Wellness External Docs


theme:
  name: material

  features:
    - navigation.indexes

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye
        name: Switch to dark mode
      primary: light green
      accent: green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
      primary: blue
      accent: deep purple




nav:
    - Welcome to Umang Wellness Guides: 'index.md'
    - General Guides:
      - general/index.md
      - Contact Support: 'general/contact-us.md'
      - View FAQs: 'general/view-faqs.md'
      - Reach Sign Up Page: 'general/reach-sign-up-page.md'
      - Reach Sign In Page: 'general/reach-sign-in-page.md'
      - Give Feedback: 'general/give-feedback.md'
      - View About Section: 'general/view-about-section.md'
      - View Cookie Policy: 'general/view-cookie-policy.md'
      - View Terms and Conditions: 'general/view-terms-and-conditions.md'
      - View Privacy Policy: 'general/view-privacy-policy.md'
      - View Sitemap: 'general/view-sitemap.md'
      - View Version History: 'general/view-version-history.md'
      - View Social Links: 'general/view-social-links.md'
      - Gift Voucher: 'general/gift-voucher.md'
    - Client Guides:
      - client/index.md
      - Sign Up: 'client/client-sign-up.md'
      - Sign In: 'client/client-sign-in.md'
      - Sign Out: 'client/client-sign-out.md'
      - Find Counsellor: 'client/find-counsellor.md'
      - View Profile Menu: 'client/view-profile-menu.md'
      - View Profile: 'client/view-profile.md'
      - Edit Profile: 'client/edit-profile.md'
      - View Counsellor List: 'client/view-counsellor-list.md'
      - Book Session: 'client/book-session.md'
      - Switch Roles: 'client/switch-roles.md'
      - Change Password: 'client/change-password.md'
      - Change Timezone: 'client/change-timezone.md'
      - Recommend Counsellor: 'client/recommend-counsellor.md'
      - View Upcoming Sessions: 'client/view-upcoming-sessions.md'
      - View Completed Sessions: 'client/view-completed-sessions.md'
      - View Cancelled Sessions: 'client/view-completed-sessions.md'
      - Reschedule Session: 'client/reschedule-session.md'
      - Buy Subscription: 'client/buy-subscription.md'
      - Update Subscription: 'client/update-subscription.md'
      - Cancel Subscription: 'client/cancel-subscription.md'
      - View Subscription Details: 'client/view-subscription-details.md'
      - Chat with Counsellor: 'client/chat-with-counsellor.md'
    - Counsellor Guides:
      - counsellor/index.md
      - Sign Up: 'counsellor/counsellor-sign-up.md'
      - Sign In: 'counsellor/counsellor-sign-in.md'
      - Sign Out: 'counsellor/counsellor-sign-out.md'
      - View Profile: 'counsellor/view-profile.md'
      - Edit Profile: 'counsellor/edit-profile.md'
      - Change Available Timings: 'counsellor/change-available-timings.md'
      - View/Edit My Pricings: 'counsellor/view-edit-my-pricings.md'
      - View Clients: 'counsellor/view-clients.md'
      - Get Approved: 'counsellor/get-approved.md'
      - Change Password: 'counsellor/change-password.md'
      - Change Timezone: 'counsellor/change-timezone.md'
      - Switch Roles: 'counsellor/switch-roles.md'
      - View Completed Sessions: 'counsellor/view-completed-sessions.md'
      - View Upcoming Sessions: 'counsellor/view-upcoming-sessions.md'
      - View Profile Menu: 'counsellor/view-profile-menu.md'
      - Cancel Session: 'counsellor/cancel-session.md'
      - Chat with Client: 'counsellor/chat-with-client.md'
      - Take Notes during Session: 'counsellor/take-notes-during-session.md'
      - Request Session Rescheduling: 'counsellor/request-session-rescheduling.md'
      - Mark Session as Completed: 'counsellor/mark-session-as-completed.md'
    - Business Flow Guide: './business-flow-guide.md'
    - Semantic Versioning: './semantic-versioning.md'
  
    